FROM node:10.16.0-jessie-slim

ARG MYSQL_HOST
ARG MYSQL_USER
ARG MYSQL_DB

ARG CONSUMER_KEY
ARG CONSUMER_SECRET
ARG ACCESS_TOKEN_KEY
ARG ACCESS_TOKEN_SECRET

ENV MYSQL_HOST $MYSQL_HOST
ENV MYSQL_USER $MYSQL_USER
ENV MYSQL_DB  $MYSQL_DB
ENV CONSUMER_KEY $CONSUMER_KEY
ENV CONSUMER_SECRET $CONSUMER_SECRET
ENV ACCESS_TOKEN_KEY $ACCESS_TOKEN_KEY
ENV ACCESS_TOKEN_SECRET $ACCESS_TOKEN_SECRET

WORKDIR 'app/'

COPY package.json .

RUN npm install

COPY . .